### ISSUE TITLE
Fehler in Home assistant nach Update "Benötigt Aufmerksamkeit"

### ISSUE THREAD

**Issue by gisbertg** [ylabonte/proconip-hass#28]
### System Health details

<img width="1061" alt="image" src="https://github.com/ylabonte/proconip-hass/assets/33952887/e1be8012-4042-4230-b86b-e3feab576f6e">

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ylabonte/proconip-hass/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Nach dem Update auf die neueste Version kommt bei mir eine Fehlermeldung.

### Reproduction steps

...

### Debug logs

```text
-
```

**Comment by ylabonte** [comment]
Könnte sein, dass das ein Nebeneffekt von Anpassungen ist, die scheinbar nötig waren, damit  man die Einstellungen zukünftig nach der EInrichtung des Adapters noch bearbeiten kann. 

1) Versuch mal bitte über die drei Punkte rechts von der Fehlermeldung, ob du da "Neu laden" auswählen kannst und ob das vielleicht schon hilft. 
2) Wenn das nicht hilft, musst du den Adapter leider über die drei Punkte entfernen und dann neu hinzufügen. 
3) Wenn das auch nicht hilft, würde ich dich bitten, den Adapter über HACS auszuwählen, dort über die drei Punkte erneut herunterzuladen und anschließend im Zweifelsfall erneut 1) und 2) versuchen. 
4) Wenn er dann noch immer nicht will, schau mal unter _Einstellungen -> System -> Protokolle_, filter dort nach "proconip" und lass mich wissen, was er dir dort ausgibt.

Ich hoffe aber eigentlich, dass schon 1) oder 2) abhilfe schafft. 😅

**Comment by ylabonte** [comment]
Ich glaube, ich konnte es gerade reproduzieren. 

Was bei mir jetzt abhilfe geschaffen hat: Ich hatte in dem Menü über die drei Punkte rechts von der Fehlermeldung die Möglichkeit "Konfigurieren" auszuwählen. Nachdem ich darüber noch einmal die Konfiguration bestätigt und anschließend über das selbe Menü "Neu laden" ausgewählt habe, ging es wieder.

**Comment by gisbertg** [comment]
Warum auch immer, ich habe in der Zwischenzeit nichts gemacht, hat sich das Problem "selber" behoben. Es läuft jetzt wieder. Sehr seltsam...

**Comment by ylabonte** [comment]
Evtl. war's ein Home Assistant neustart, der durch ein Core Update oder so veranlasst wurde, der das Problem zwischenzeitlich behoben hat.

Ich fürchte zwar, dass ich es mit meinem letzten Update verschuldet habe, aber das ist dann jetzt wohl der Preis dafür, dass man die Konfiguration nun jederzeit anpassen kann. 😅 Solange das Problem nur nach dem Update und zukünftig nicht wieder auftritt...

**Comment by tluethi71** [comment]
Zuerst mal danke für dein Modul... Super..

Ich habe selbes Problem. Jedoch hat es sich noch nicht von selbst gelöst. Wenn ich auf die Version 1.0.2. gehe, funktioniert es, dann werden die Entitäten erstellt. Wenn ich dann wiederum auf 1.1.0 update, gehts wiederum nicht mehr...
