### ISSUE TITLE
Falsely "Cannot permanently switch on a dosage relay"

### ISSUE THREAD

**Issue by Syonis** [ylabonte/proconip-hass#56]
## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4881
Installed Version | 1.34.0
Stage | running
Available Repositories | 1401
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.0 GB
disk_used | 13.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Terminal & SSH (9.10.0), evcc (0.124.10), Node-RED (17.0.9), Mosquitto broker (6.4.0), File editor (5.8.0), FTP (5.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 9
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7. März 2024 um 09:16
-- | --
current_recorder_run | 16. März 2024 um 10:09
estimated_db_size | 1632.32 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ylabonte/proconip-hass/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

On my Relay No 5 is a Bypass for my Heatpump. When I want to switch it on it says "poolcontroller switch/turn_on. Cannot permanently switch on a dosage relay" But my Chlorine and PH- are on Relay 7 and 8.
So Im not able to control my Heatpump-Bypass with HomeAssistant. Turning the Bypass OFF is indeed possible.
Oh, and I have to say, that my Poolcontroller is about 12 Years old ;) Perhaps they changed the Relays.
### Reproduction steps

Try to switch Relay 5 with this.

**Comment by ylabonte** [comment]
Hi, my guess is that you have relay no. 5 configured as pH+ dosage relay. This would block relay no. 5 regardless of the fact, if pH+ dosage itself is enabled or disabled. 

If this is the case, please chose relay 7 or 8 as your pH+ dosage relay as well (keeping pH+ dosage itself deactivated), then remove and re-add the home assistant integration.

**Comment by Syonis** [comment]
Nope, Relay No. 5 is for my Bypass. Since the beginning. 
<img width="1001" alt="Screenshot_20240319_153302" src="https://github.com/ylabonte/proconip-hass/assets/97046583/8252df1e-578e-4818-bc57-10693d0cb6c6">
I've managed it with a quick and dirty solution right now.
```
command_line:
  - switch:
        name: poolcontoller_rel5_http
        command_on: /usr/bin/curl -s "http://192.168.5.17/SetState.pl?R5=1&RT5=0"
        command_off: /usr/bin/curl -s "http://192.168.5.17/SetState.pl?R5=0&RT5=0"
```

**Comment by Syonis** [comment]
Jep... that it. Thanks a lot... I've never ever looked at pH+.

**Comment by lordvalium** [comment]
Hi, 
i have my lamps at Relais 5 but i get the same error, what can i do? Thanks

![image](https://github.com/ylabonte/proconip-hass/assets/2970225/fd10404c-400b-4f7c-bcbe-fba234cb1e5c)

**Comment by Syonis** [comment]
Change in "pH+ Dosierung" "Dosierpumpe" to another Relais.

<img width="836" alt="Screenshot_20240319_204022" src="https://github.com/ylabonte/proconip-hass/assets/97046583/73d1a9ad-bcaf-4234-80a5-858509b319ec">

**Comment by lordvalium** [comment]
Cool thanks will try today night :)
